version: "3.3"
services:

  app:
    container_name: gomdb_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
      - backend

  db:
    container_name: gomdb_db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gomdb
    ports:
      - 5432:5432
    networks:
      - backend
    healthcheck:
      test: pg_isready -U postgres -d gomdb
      interval: 10s
      timeout: 3s
      retries: 5
  
  # migrate:
  #   container_name: gomdb_migrations
  #   image: migrate/migrate
  #   networks:
  #     - backend
  #   volumes:
  #     - .:/migrations
  #   command: ["-path", "/migrations", "-database",  "postgres://postgres:password@db:5432/gomdb?sslmode=disable", "up"]
  #   links:
  #     - db
  #   depends_on:
  #     - db

networks:
  backend:
    name: backend-network
    driver: bridge